site_name: "Tardim: In Control"
site_description: "Documentation for mod TARDIM: In Control"
site_author: Andrew_7_1

copyright: Copyright © 2023 Andrey N.

nav:
  - Home:
      - Home: "index.md"
  - Features:
      - Blocks:
        - Redstone Input: blocks/redstone_input.md
      - Commands: commands.md
      - Changes to TARDIM: mixins.md
  - ComputerCraft compatibility:
      - computercraft/index.md
      - Peripherals:
        - Digital TARDIM Interface: computercraft/peripherals/digital_interface.md
        - Fuel Storage Block: computercraft/peripherals/fuel_storage.md
        - TARDIM Scanner Block: computercraft/peripherals/tardim_scanner.md
        - Time Rotor Block: computercraft/peripherals/time_rotor.md
  - Create compatibility:
      - create/index.md
#      - Display Sources:
#        - Fuel Storage Block: create/sources/fuel_storage.md
#        - TARDIM Scanner Block: create/sources/tardim_scanner.md
#        - Time Rotor Block: create/sources/time_rotor.md
  - Planned features:
      - planned.md

site_url: https://tardim.a71.su/
repo_name: Andrew71/Tardim-In-Control
repo_url: https://git.a71.su/Andrew71/Tardim-In-Control
#edit_uri: https://git.a71.su/Andrew71/Tardim-In-Control/src/branch/1.20/docs

theme:
  name: readthedocs

  features:
    - content.code.copy
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.indexes

  font: false
  palette:
    scheme: slate
    primary: custom
    accent: custom

  favicon: assets/img/icon.png

extra_css:
  - assets/style.css