site_name: "Tardim: In Control"
site_description: "Documentation for mod TARDIM: In Control"
site_author: Andrew_7_1

copyright: Copyright © 2023 Andrey N.

nav:
  - Home:
      - Home: "index.md"
  - Crafting recipes:
      - Recipes: "recipes.md"
  - ComputerCraft compatibility:
      - computercraft/index.md
      - Peripherals:
        - Digital TARDIM Interface: computercraft/peripherals/digital_interface.md
        - Fuel Storage Block: computercraft/peripherals/fuel_storage.md
        - TARDIM Scanner Block: computercraft/peripherals/tardim_scanner.md
        - Time Rotor Block: computercraft/peripherals/time_rotor.md
  - Guides:
      - guides/index.md
      - Wrenches and You: guides/wrenches.md
      - "Using Animatronics: The Analog Way": guides/positioningAnimatronicAnalog.md

site_url: https://tardim.a71.su/
repo_name: Andrew71/Tardim-In-Control
repo_url: https://git.a71.su/Andrew71/Tardim-In-Control
edit_uri: https://git.a71.su/Andrew71/Tardim-In-Control/src/branch/1.20/docs

extra:
  social:
    - icon: simple/modrinth
      link: https://modrinth.com/mod/tardim_ic
      name: Modrinth
    - icon: simple/curseforge
      link: https://www.curseforge.com/minecraft/mc-mods/tardim_ic
      name: CurseForge

markdown_extensions:
  - attr_list

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition
  - pymdownx.details

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - toc:
      permalink: true

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - social:
  - glightbox:
  - search:

theme:
  name: material

  features:
    - content.code.copy
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.indexes

  font: false
  palette:
    scheme: slate
    primary: custom
    accent: custom

  icon:
    repo: fontawesome/brands/git
  logo: assets/images/cccbridge-icon.png
  favicon: assets/images/tweaked-programs-icon.png

extra_css:
  - assets/stylesheets/extra.css